version: '2'
services:
  mysql:
    image: novosti/mysql
    build: ./docker/mysql/.
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  backend:
    image: novosti/backend
    build: ./docker/backend/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "28001:8000"
    links:
      - mysql
