version: '2'
services:
  postgres:
    image: postgres:9.4
  mysql:
    image: novosti/mysql
    build: ./docker/mysql/.
    ports:
      - "3306:3306"
  backend:
    image: novosti/backend
    build: ./docker/backend/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mysql
