version: '2'
services:
  mysql:
    image: novosti/mysql
    build: ./docker/mysql/.
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "main"
      MYSQL_USER: "django"
      MYSQL_PASSWORD: "Passw0rd"
      MYSQL_ROOT_PASSWORD: "Passw0rd"
  backend:
    image: novosti/backend
    build: ./docker/backend/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "28001:8000"
    links:
      - mysql
